### DISCUSSION TITLE
ROM BASIC - how to enable it

### DISCUSSION THREAD

**Discussion by Torinde** [dbalsom/marty#125] [Q&A] [answered]
I put IBMROMBASIC-F6000h-1982-10-27.ROM in `\media\rom`, but GLaBIOS still finishes by saying there's no bootable drive, "you monster" :)

should I put `ibm_basic` somewhere in a configuration file? And what should be the filename and place of the .ROM file?

Also, I want to try memory sizes [lower than 64KB](https://github.com/joncampbell123/dosbox-x/issues/3664#issuecomment-2182430832), but it seems GLaBIOS doesn't support that (I get blank screen in MartyPC). I have IBM PC BIOS files, but where should I put them and how to .... sorry, now I see [readme](https://github.com/dbalsom/martypc/tree/version_0_2_2/install/media/roms), leading to Wiki, leading to Definitions... 

I will read those first before continuing asking questions.

**Comment by dbalsom** [comment]
try starting MartyPC from a cmd window/terminal and watching the output. You should see something like:

```
Selected machine config ibm5160 has resolved the following ROM sets:
  glabios_xt_turbo
  ibmbasic_v1_32k
```

Let me know the MD5 of "IBMROMBASIC-F6000h-1982-10-27.ROM" if it is not auto-detecting it. ROM BASIC is considered an "optional" feature so it will not cause an error if it is not found.

You'd have to ask 640KB about the RAM thing. I don't know what GLaBIOS' minimum RAM requirement is. You'll need to use the `ibm5150_64k` machine if you want to have less than 64K of RAM and you'll probably want to use the IBM BIOS. I haven't really tested all the various RAM configurations so there might be bugs there, but I think that should let you go down to 16K.  I don't think anything will actually boot in 16K, though.

**Reply by Torinde** [reply]
MD5 hash of IBMROMBASIC-F6000h-1982-10-27.ROM:
eb28f0e8d3f641f2b58a3677b3b998cc

- https://github.com/640-KB/GLaBIOS/discussions/50#discussioncomment-9847336
>> does GLaBIOS support 16KB models?

> Yes, I have a real 16K-64K 5150 and have tested GLaBIOS thoroughly on it and works well.

I get blank screen in MartyPC, but maybe I didn't configure something properly.

As for booting something - BASIC works in 86Box. And PC DOS 1.00 reportedly works on real PC in a [quasi-16KB/32KB mode](https://github.com/joncampbell123/dosbox-x/issues/3664#issuecomment-2182430832).

**Reply by dbalsom** [reply, marked as answer]
> MD5 hash of IBMROMBASIC-F6000h-1982-10-27.ROM: eb28f0e8d3f641f2b58a3677b3b998cc

Ok, I do not have this particular version of the BASIC rom. Is this 1.0 or 1.1?

EDIT: Found a reference to it.

You can modify your `romdef_ibm.toml` file as follows:

```toml
[[romset]]
alias = "ibmbasic_v11_32k"
desc = "IBM Cassette Basic C1.10"
priority = 2
provides = ["ibm_basic"]
oem = true
rom = [
    { md5 = "2ad31da203a49b504fad3a34af0c719f", addr = 0xF6000, size = 32768, chip = "c" },
    { md5 = "eb28f0e8d3f641f2b58a3677b3b998cc", addr = 0xF6000, size = 32768, chip = "c" },
]
```
