### DISCUSSION TITLE
COM ports (mouse)

### DISCUSSION THREAD

**Discussion by llyon1965** [dbalsom/marty#52] [Ideas]
Can I suggest that having a mouse on COM1 is optional rather than enforced ?

**Comment by dbalsom** [comment]
Yes; I hope to make machine configuration much more flexible in general overall.

**Reply by llyon1965** [reply]
That's great news - thank you.

**Reply by dbalsom** [reply]
It's been a while, hope you haven't lost interest!  I've implemented machine configurations. So you can now attach a mouse like so:

```toml
[[machine]]
name = "generic_xt_hdd_ega"
type = "Ibm5160"
rom_set = "glabios_xt"
speaker = true

# ... omitting rest of config ...
    
    [machine.serialmouse]
    type = "Microsoft"
    port = 0

```
